version: '2'
services:
  vole-eureka:
    container_name: app-eureka
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
      - 1025:1025

  vole-config:
    links:
      - vole-eureka:eureka
    container_name: app-config
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always

  vole-portal-data:
    links:
      - vole-eureka:eureka
    container_name: app-portal-data
    build:
      context: ./
      dockerfile: Dockerfile-portal-data
    restart: always

  vole-portal:
    links:
      - vole-eureka:eureka
    container_name: app-portal
    build:
      context: ./
      dockerfile: Dockerfile-portal
    restart: always

  vole-passport:
    links:
      - vole-eureka:eureka
    container_name: app-passport
    build:
      context: ./
      dockerfile: Dockerfile-passport
    restart: always

  vole-mps:
    links:
      - vole-eureka:eureka
    container_name: app-mps
    build:
      context: ./
      dockerfile: Dockerfile-mps
    restart: always

  vole-auth:
    links:
      - vole-eureka:eureka
    container_name: app-auth
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always
    ports:
      - 3000:3000

  vole-gateway:
    links:
      - vole-eureka:eureka
      - vole-auth:auth
    container_name: app-gateway
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 9999:9999




