cp ./app-portal-data/target/app-portal-data-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-portal-data.jar
cp ./app-modules/app-job/target/app-job-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-job.jar
cp ./app-modules/app-ssoclient/target/app-ssoclient-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-ssoclient.jar
cp ./app-modules/app-turbine/target/app-turbine-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-turbine.jar
cp ./app-modules/app-mq/target/app-mq-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-mq.jar
cp ./app-modules/app-casclient/target/app-casclient-0.0.1-SNAPSHOT.jar /home/app/docs/docker/jar/app-casclient.jar
cp ./app-modules/app-message/target/app-message-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-message.jar
cp ./app-auth/target/app-auth-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-auth.jar
cp ./app-gateway/target/app-gateway-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-gateway.jar
cp ./app-portal-common/target/app-portal-common-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-portal-common.jar
cp ./app-portal/target/app-portal-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-portal.jar
cp ./app-config/target/app-config-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-config.jar
cp ./app-demo/target/app-demo-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-demo.jar
cp ./app-mps/target/app-mps-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-mps.jar
cp ./app-passport/target/app-passport-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-passport.jar
cp ./app-passport-common/target/app-passport-common-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-passport-common.jar
cp ./app-eureka/target/app-eureka-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-eureka.jar
cp ./app-common/target/app-common-1.0.0-SNAPSHOT.jar /home/app/docs/docker/jar/app-common.jar
