cp ./vole-portal-data/target/vole-portal-data-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-portal-data.jar
cp ./vole-modules/vole-job/target/vole-job-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-job.jar
cp ./vole-modules/vole-ssoclient/target/vole-ssoclient-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-ssoclient.jar
cp ./vole-modules/vole-turbine/target/vole-turbine-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-turbine.jar
cp ./vole-modules/vole-mq/target/vole-mq-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-mq.jar
cp ./vole-modules/vole-casclient/target/vole-casclient-0.0.1-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-casclient.jar
cp ./vole-modules/vole-message/target/vole-message-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-message.jar
cp ./vole-auth/target/vole-auth-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-auth.jar
cp ./vole-gateway/target/vole-gateway-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-gateway.jar
cp ./vole-portal-common/target/vole-portal-common-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-portal-common.jar
cp ./vole-portal/target/vole-portal-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-portal.jar
cp ./vole-config/target/vole-config-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-config.jar
cp ./vole-demo/target/vole-demo-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-demo.jar
cp ./vole-mps/target/vole-mps-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-mps.jar
cp ./vole-passport/target/vole-passport-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-passport.jar
cp ./vole-passport-common/target/vole-passport-common-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-passport-common.jar
cp ./vole-eureka/target/vole-eureka-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-eureka.jar
cp ./vole-common/target/vole-common-1.0.0-SNAPSHOT.jar /home/vole/docs/docker/jar/vole-common.jar
