version: '3'
services:
  redis: 
    image: redis:alpine
    container_name: app-redis
    restart: always
    volumes:
      - ../data/redis:/data
    environment:
      - REDIS_PASSWORD=
    networks:
      - app-net
    ports:
      - 6379:6379
    env_file: .env

  rabbitmq:
    image: rabbitmq:alpine
    container_name: app-rabbitmq
    restart: always
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - app-net
    ports:
      - 5672:5672
    env_file: .env

  mysql:
    image: mysql:8.0.17
    container_name: app-mysql
    restart: always
    networks:
      - app-net
    ports:
      - 3306:3306
    volumes:
      - ../data/mysql:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: vole
      lower_case_table_names: 1

  mysql-init:
    image: mysql:8.0.17
    container_name: app-mysql-init
    links:
      - mysql
    networks:
      - app-net
    volumes:
      - ../db:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 12345678

networks:
  app-net:
    external: false